### PR TITLE
Translation features

### PR DESCRIPTION
**Pull request by doc-sebastian**
Dear Aysel,
I added the base for a dynamic translation of your wonderful DicomViewer. My small patch automatically translates everything except the message "There is no available DICOM image to display" and all the names of the viewer tools in the toolbar depending on your locale and NC language settings. Now it's easy for other people adding further languages next to my German translation.
Is there any chance to establish translation of the terms in the javascript files as well?

### CODE REVIEW

**Comment by ayselafsar** [comment]
Hi @doc-sebastian,

Thanks for PR, I will take a look ASAP.

**Comment by ayselafsar** [comment]
Could you please update this PR to work with the latest changes in master? 

FYI, I moved all php templates from 'templates' folder into html templates under 'js/components/templates' folder.

Thanks for your contribution!

**Comment by Lars1963** [comment]
@ayselafsar can you make the app being translatable through transifex (just like all other Nextcloud-apps)?  So the userlanguages can be made easier available. :-) For me, I can translate in German and in Dutch.

**Comment by doc-sebastian** [comment]
> Could you please update this PR to work with the latest changes in master?
> 
> FYI, I moved all php templates from 'templates' folder into html templates under 'js/components/templates' folder.
> 
> Thanks for your contribution!

Unfortunately the conflicts of the pull request cannot be resolved and the request cannot be merged anymore :-/ I tried to move the templates and reupload the patch-2 but it doesn't help....

**Comment by doc-sebastian** [comment]
Dear Aysel,
Seems to be too complicated for me. I already tried to fork your current 
master another time to do it manually but Github doesn't let me fork it 
again without deleting my current fork - which  means loosing my  grayscale 
stylesheet mods :-(


Am 29. Dezember 2018 17:22:49 schrieb Aysel Afsar <notifications@github.com>:

**Comment by ayselafsar** [comment]
Closing this PR since #32

**Pull request closed without merging**
