### PR TITLE
Drop support for nc12

### PR DESCRIPTION
**Pull request by Lars1963**
As nextcloud 12 has reached eol and is no longer supported, dicomviewer should also no longer be used on nc12.

### CODE REVIEW

**Comment by doc-sebastian** [comment]
Let's hope NC12 support will not be dropped. I'm still using it ;-)

**Comment by Lars1963** [comment]
> Let's hope NC12 support will not be dropped. I'm still using it ;-)
Nextcloud strongly suggest you should update. Especially because of securityreasons and eol of php 5.4 and 7.0. I hope you don't use that too! ;-((

**Comment by doc-sebastian** [comment]
> Let's hope NC12 support will not be dropped. I'm still using it ;-)

Unfortunately my NC12 doesn't work with release 1.1.0 anymore. Any idea if this can be fixed / workaround? Is it due to fixing compatibility issues for NC15?

**Comment by Lars1963** [comment]
@doc-sebastian 
Another reason to update your nc! The plus in working performance in nc 15 is just incredible. ;-)

**Comment by ayselafsar** [comment]
@doc-sebastian Could you please create an issue with browser logs, because i have tested 1.1.0 in NC12 as well, and didn't see any issue. It would be good to see what is wrong. Thanks.

**Comment by ayselafsar** [comment]
@Lars1963 you need to update this PR to have changes only to drop NC12 support, not the deleted translation files.

BTW, i would keep NC12 support for a while.

**Comment by Lars1963** [comment]
New PR to be submitted

**Pull request closed without merging**
