### PR TITLE
Only load DICOM viewer CSS/JS on the Files app

### PR DESCRIPTION
**Pull request by Lars1963**
1. Partialy closes PR #27 
2. Part of closed PR #34 

@ayselafsar Please review. Your former review has been added

### CODE REVIEW

**Comment by ayselafsar** [comment]
FYI, I reverted this PR back since it prevents loading dicom viewer app on public sharing links. That is not something we want.

**Comment by Lars1963** [comment]
OK. Indeed that is not wanted.

**Comment by Rello** [comment]
Hello @ayselafsar 
can I suggest to re-revert it? :-)

you just need to add a second file dispatcher for the file-share.
I had the same issue with Audioplayer

https://github.com/Rello/audioplayer/blob/master/appinfo/app.php#L34

thank you for reconsidering.
the loading of unnecessary files should be avoided as far as possible.

**Comment by Rello** [comment]
`'OCA\Files_Sharing::loadAdditionalScripts'`

**Pull request merged**
