### PR TITLE
Additional Translations

### PR DESCRIPTION
**Pull request by Lars1963**
I added Dutch and non-formal German translations, Furthermore I updated the formal German translations.   
( @doc-sebastian: Can you please review the german files?).

@ayselafsar 
I'm still trying to figure out how to make the js-files l10n compatible (in php its seems very easy to me, as we can add "use OCP\l10n"). Can you please point out to me, where you have the appropriate strings in the files? I guess, I have to buils an extra class for the translations?

### CODE REVIEW

**Comment by doc-sebastian** [comment]
Here is what it looks like with shorter Translations:
https://github.com/doc-sebastian/dicomviewer/blob/master/screenshots/viewer1.jpg

**Comment by Lars1963** [comment]
Yes. I think too, we have to change the length of some of the translated strings. Alltough with a wide screen. it is not so much of a problem. Lets us first get the l10n-integration in the js-files working.

**Comment by ayselafsar** [comment]
Thanks for the PR. I am going to merge this PR to development branch. Then I will add l10n integration for js and html files.

**Comment by ayselafsar** [comment]
@Lars1963 @doc-sebastian 

I pushed l10n integration for js and html files into development branch. Please check the development branch and create PR for missing translations to that branch. I will try to integrate transifex when I have time.

Here is some missing translations I noticed:

- Open with DICOM Viewer
- Length
- Lossless / Uncompressed
- Lossy: 
- WW/WC
- OK
- Less

Again, thanks for your contributions!

**Pull request merged**
